export const mockDoctors = [
     {
          id: 1,
          name: 'dr. Andi Wijaya, Sp.PD',
          specialization: 'Penyakit Dalam',
          licenseNumber: 'SIP-001-2024',
          phone: '081234567890',
          email: 'andi.wijaya@primahusada.com',
          experience: 10,
          status: 'Aktif',
     },
     {
          id: 2,
          name: 'drg. Budi Santoso',
          specialization: 'Gigi',
          licenseNumber: 'SIP-002-2024',
          phone: '081234567891',
          email: 'budi.santoso@primahusada.com',
          experience: 7,
          status: 'Aktif',
     },
     {
          id: 3,
          name: 'dr. Siti Aminah, Sp.OG',
          specialization: 'Kebidanan',
          licenseNumber: 'SIP-003-2024',
          phone: '081234567892',
          email: 'siti.aminah@primahusada.com',
          experience: 12,
          status: 'Aktif',
     },
     {
          id: 4,
          name: 'dr. Rizki Ramadhan, Sp.Rad',
          specialization: 'Radiologi',
          licenseNumber: 'SIP-004-2024',
          phone: '081234567893',
          email: 'rizki.ramadhan@primahusada.com',
          experience: 8,
          status: 'Aktif',
     },
];
