export const mockLabTests = [
     {
          id: 1,
          patientId: 1,
          testCode: 'LAB-2024-0001',
          category: 'Hematologi',
          testType: 'Darah Lengkap',
          testDate: new Date('2024-01-05'),
          status: 'Selesai',
          priority: 'Normal',
          patientName: 'Budi Setiawan',
          doctor: 'dr. Andi Wijaya, Sp.PD',
          results: {
               hemoglobin: '14.5',
               leukosit: '8500',
               eritrosit: '4.8',
               trombosit: '250000',
          },
          notes: 'Hasil normal',
          patients: {
               id: 1,
               name: 'Budi Setiawan',
          },
     },
     {
          id: 2,
          patientId: 2,
          testCode: 'LAB-2024-0002',
          category: 'Kimia Darah',
          testType: 'Gula Darah Puasa',
          testDate: new Date('2024-01-06'),
          status: 'Dalam Proses',
          priority: 'High',
          patientName: 'Dewi Kusuma',
          doctor: 'dr. Andi Wijaya, Sp.PD',
          results: null,
          notes: 'Sedang diproses',
          patients: {
               id: 2,
               name: 'Dewi Kusuma',
          },
     },
     {
          id: 3,
          patientId: 3,
          testCode: 'LAB-2024-0003',
          category: 'Hematologi',
          testType: 'Golongan Darah',
          testDate: new Date('2024-01-07'),
          status: 'Menunggu Sample',
          priority: 'Normal',
          patientName: 'Ahmad Fauzi',
          doctor: 'dr. Siti Aminah, Sp.OG',
          results: null,
          notes: '',
          patients: {
               id: 3,
               name: 'Ahmad Fauzi',
          },
     },
];
